Updated guide to use set.props.dotNotation
donejs/donejs pull request #909
Opened 2017-04-13 21:47 UTC by nlundquist

Updates PMO guide to reflect changes in can-set stemming from #900

2017-04-13 21:50 UTC, nlundquist commented on docs/guides/place-my-order.md
> +Above we use 'set.props.dotNotation' since our queries for these nested properties will be in the MongoDB-style 'dot notation' format required by the backend.
Think I should add a link to the Mongo docs that describe why dot notation is relevant?

2017-04-13 22:22 UTC, nlundquist commented
Is there an open issue for fixing the travis tests? I don't believe they're failing due to my changes.

2017-04-14 15:13 UTC, matthewp commented
@nlundquist i'm going to look into the build failures.

2017-04-14 15:17 UTC, phillipskevin commented on docs/guides/place-my-order.md
> +Above we use 'set.props.dotNotation' since our queries for these nested properties will be in the MongoDB-style 'dot notation' format required by the backend.
A link would be fine, but maybe just an example of what the query params look like would be good enough to explain what this does.

2017-04-14 17:05 UTC, phillipskevin requested changes
I would either just add a comment explaining how `props.dotNotation` affects the query params or a link to the Mongo docs. Otherwise looks good!

2017-04-14 18:24 UTC, nlundquist commented
![both](https://cloud.githubusercontent.com/assets/2623867/25052089/502c743e-210d-11e7-82c8-e04b2cb4e1ae.gif)

2017-04-14 19:26 UTC, phillipskevin commented on docs/guides/place-my-order.md
> +For example, MongoDB expects a query parameter for restaurants in a specific state to look like `{'address.state':'IL'}` and the libraries underneath supermodel expect it to look like `{address:{stat
maybe instead of 
> the libraries underneath supermodel

just say "can-connect" ?

2017-04-14 23:15 UTC, phillipskevin requested changes

2017-04-14 23:15 UTC, phillipskevin commented on docs/guides/place-my-order.md
> +For example, MongoDB expects a query parameter for restaurants in a specific state to look like `{'address.state':'IL'}` and the can-connect expect it to look like `{address:{state: 'IL'}}`. `set.pro
> and the can-connect expect

should be

> and can-connect expects

2017-04-17 14:08 UTC, matthewp commented
I'm pretty sure the tests failing is caused by https://github.com/stealjs/steal/issues/1172. I'm working on that now.

2017-04-17 15:12 UTC, nlundquist commented on docs/guides/place-my-order.md
> +For example, MongoDB expects a query parameter for restaurants in a specific state to look like `{'address.state':'IL'}` and the can-connect expect it to look like `{address:{state: 'IL'}}`. `set.pro
doh! got that fixed

2017-04-17 15:16 UTC, phillipskevin approved these changes

2017-04-17 19:20 UTC, matthewp commented
Tests are passing again. Anything left to do here @nlundquist @phillipskevin ?

2017-04-17 19:36 UTC, matthewp commented
@nlundquist says it's ready 🛳

2017-04-17 19:36 UTC, merged