Fixes #911. Adds 'new' as to create a new project
donejs/donejs pull request #932
Opened 2017-05-02 16:57 UTC by mjstahl

Adds a `donejs new <folder>` command that creates and initializes a new DoneJS application in `<folder>`.

2017-05-19 16:06 UTC, andrejewski commented
Sorry, I did not get the notification for review and stumbled on to this by chance. I'd like to see some tests for this, but since there are no direct bin/donejs CLI tests this is fine. I'll pull this down locally and try it out before I approve but then I will be content.

2017-05-22 13:38 UTC, andrejewski requested changes
`new` should be an alias of `add` and have its own usage docstring

2017-05-22 13:38 UTC, andrejewski commented on lib/cli/index.js
> +program.command('new <folder>')
For the `new` command, it should be able to create apps, plugins, or generators; not only only new apps. It's essentially the same as add. The word **new** just better articulates the creation effect of commands, which is a convention other CLI tools align with.

2017-05-22 13:38 UTC, andrejewski commented on lib/cli/index.js
> +  .action(function(folder, params) {
For the `new` command we should also have the usage information like `add` does.

2017-05-22 14:08 UTC, andrejewski approved these changes

2017-05-25 15:15 UTC, chasenlehara requested changes
Code looks good, just needs docs and [tests](https://github.com/donejs/donejs/tree/master/test)! I think they should be added to this section: https://github.com/donejs/donejs/blob/master/docs/apis.md#cli-and-generators

2017-07-24 15:51 UTC, frank-dspeed commented
As pointed out in the related issue 
- #911. Adds 'new' as to create a new project 

i would suggest to talk about #995 and don't change existing docs and api

2019-05-07 19:52 UTC, closed without merging